### ISSUE TITLE
The question of dataset .

### ISSUE THREAD

**Issue by EthanCodesss** [louisccc/sg-risk-assessment#36]
Hello! Your work is excellent. The IEEE DataPort seems doesn't work for me.  Would you mind upload it by google drive or other forms? I will thank you very much！

**Comment by Brandhsu** [comment]
Hi apologies for the delayed response. If you are still interested in accessing the dataset you can do so by accessing https://ieee-dataport.org/documents/scenegraph-risk-assessment-dataset

create an account, then create a subscription at https://ieee-dataport.org/subscribe

You will need to input payment information, but can apply the coupon `DATAPORT1` at checkout to get a free subscription. 

After this you should be able to access the dataset zip file.
