### ISSUE TITLE
The question about raw data

### ISSUE THREAD

**Issue by Doha7430** [louisccc/sg-risk-assessment#41]
Hello, thank you for providing the dataset of scene-graph, your paper provides a lot of help! I am participating in similar work in this field, and I'd like to ask, could you provide the original data of images before generating the scene-graph? It is more helpful to promote works in this field. Thank you again！

**Comment by Brandhsu** [comment]
Hi the original images are available in the dataport as `syn-271-image` and `syn-1043-image`.

**Comment by kenshohara** [comment]
Hi, I also try to use your syn-271 and syn-1043 datasets. However, syn-271-image and syn-1043-image include only very low resolution images (64x36 pixels). Do I not understand the data correctly? I think it is difficult to detect objects from such low resolution images to generate scene graphs.

**Comment by malawada** [comment]
Hello, thanks for the query. We will upload the raw data/images for the syn datasets to the dataport soon.

**Comment by malawada** [comment]
Hello, we have updated the dataport to now include the raw image data, raw frame-dictionaries containing the scene description, and risk labels as well. You can find it in 1043.zip on the dataport link.

**Comment by kenshohara** [comment]
Thank you for uploading! I'm trying to download the file.

**Comment by zakaria-hajjaji** [comment]
hey guys is there anyone has executed the project on colab ? cuz im struglling with scene graph extraction

**Comment by malawada** [comment]
Hello, please check our newer more complete repository which contains code for data generation, scene graph extraction, and learning as well:
https://github.com/AICPS/roadscene2vec
