### ISSUE TITLE
ImportError: cannot import name 'FastRGCNConv'

### ISSUE THREAD

**Issue by xinxinlv** [louisccc/sg-risk-assessment#51]
Hi, I got an error as follows.
```
Traceback (most recent call last):
  File "sg_risk_assessment.py", line 7, in <module>
    from sg_risk_assessment.dynkg_trainer import *
  File "D:\liuxx\sg-risk-assessment-master\sg_risk_assessment\dynkg_trainer.py", line 22, in <module>
    from sg_risk_assessment.mrgcn import *
  File "D:\liuxx\sg-risk-assessment-master\sg_risk_assessment\mrgcn.py", line 6, in <module>
    from torch_geometric.nn import RGCNConv, SAGPooling, TopKPooling, FastRGCNConv
ImportError: cannot import name 'FastRGCNConv'
```
how to solve this problem?😭

**Comment by xinxinlv** [comment]
maybe my ‘torch_geometric’ version is not correct.

**Comment by malawada** [comment]
This is most likely a torch geometric issue. Please check your version and that you can do 'import torch_geometric' and 'from torch_geometric.nn import FastRGCNConv'. If it doesnt work you may need to reinstall or upgrade to the latest version.

**Comment by xinxinlv** [comment]
Thank you! I'd like to ask that, how can I get the 'model_best_val_loss_.vec.pt' to load for training?&nbsp;This project does not contain a folder named 'model'. Thank you again!



---Original---
From: "Arnav ***@***.***&gt;
Date: Tue, Oct 25, 2022 07:08 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [louisccc/sg-risk-assessment] ImportError: cannot import name'FastRGCNConv' (Issue #51)




 
This is most likely a torch geometric issue. Please check your version and that you can do 'import torch_geometric' and 'from torch_geometric.nn import FastRGCNConv'. If it doesnt work you may need to reinstall or upgrade to the latest version.

**Comment by malawada** [comment]
We did not provide a pretrained model for this repository. However, in our new repository we have a more comprehensive implementation of this code along with pretrained models and datasets: https://github.com/AICPS/roadscene2vec

The risk assessment use case in roadscene2vec uses the same model architecture as this repository.
